routes/web.php
<?php

use App\Http\Controllers\Dashboard\AuthController;
use App\Http\Controllers\Dashboard\HomeController;
use App\Http\Controllers\Dashboard\ProjectController;
use App\Http\Controllers\Dashboard\TaskController;
use App\Http\Controllers\Dashboard\TasktController;
use App\Http\Controllers\Dashboard\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});


Route::group(['prefix' => 'dashboard',], function () {
    Route::get('/login', [AuthController::class, 'login'])->name('dashboard.login');
    Route::post('/login', [AuthController::class, 'adminLogin'])->name('dashboard.submit.login');
    Route::any('/logout', [AuthController::class, 'logout'])->name('dashboard.logout');

    // Route::group(['middleware' => 'auth'], function () {

    Route::get('home', [HomeController::class, 'home'])->name('dashboard.home');

    Route::resource('projects', ProjectController::class);
    Route::post('/ajax-delete-project', [ProjectController::class, 'delete'])->name('ajax-delete-project');

    Route::resource('tasks', TaskController::class);
    Route::post('/ajax-delete-tasks', [ProjectController::class, 'delete'])->name('ajax-delete-task');

//
    Route::resource('users', UserController::class);
    Route::post('/ajax-delete-user', [UserController::class, 'delete'])->name('ajax-delete-user');
    // });
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public function project()
    {
        return $this->belongsTo(Project::class,'project_id', 'id');
    }

}

app/Http/Controllers/Api/TaskController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\createTaskRequest;
use App\Http\Requests\Api\UpdateTaskRequest;
use App\Http\Resources\Api\TaskResource;
use App\Models\Task;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    public function create(createTaskRequest $request)
    {
        $data = $request->all();
        $task = Task::create($data);

        return response()->json(['status' => 'success', 'message' => 'added successfully', 'data' => new TaskResource($task)], 200); //CREATED
    }

    public function update(UpdateTaskRequest $request)
    {
        $task = Task::where(['id' => $request->task_id])->first();
        if (!$task)
            return response()->json(['status' => 'fails', 'message' => 'not found', 'data' => null], 400);//NOT_FOUND

        $task->update($request->validated());
        return response()->json(['status' => 'success', 'message' => 'updated successfully', 'data' => new TaskResource($task)], 200); //CREATED
    }

    public function delete(Request $request, $id)
    {
        $task = Task::find($id);
        if ($task) {
            $task->delete();
            return response()->json(['status' => 'success', 'message' => 'deleted-successfully', 'data' => ""], 200); //OK
        }
        return response()->json(['status' => 'fails', 'message' => 'there is no tasks.', 'data' => null], 403);//not found

    }

}

app/Http/Controllers/Dashboard/AuthController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    public function login()
    {
        return view('dashboard.auth.login');
    }


    public function adminLogin(Request $request)
    {
        $request->validate([
            'email' => 'required',
            'password' => 'required'
        ]);

        $remember = isset($request['remember']) ? $request['remember'] : false;

        if (Auth::attempt(['email' => $request->email, 'password' => $request->password], $remember)) {
            return redirect()->route('dashboard.home');
        }
        return back()->with('message', 'يرجى التأكد من صحة الايميل والباسورد.')->with('class', 'alert-danger');
    }


    public function logout()
    {
        Auth::guard('web')->logout();

        return redirect(route('dashboard.login'));
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\adminUpdateRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;

class HomeController extends Controller
{
    public function home()
    {
        $data['users_count'] = \App\Models\User::count();
        $data['projects_count'] = \App\Models\Project::count();
        $data['tasks_count'] = \App\Models\Task::count();


        return view('dashboard.index',$data);
    }






}

app/Http/Controllers/Dashboard/ProjectController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\AddProjectRequest;
use App\Models\Project;
use App\Models\Task;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProjectController extends Controller
{
    public function index()
    {
        $projects = Project::with('user')->get();
        return view('dashboard.Projects.index', compact('projects'));
    }

    public function create()
    {
        $data['latest_projects'] = Project::orderBy('id', 'desc')->take(10)->get();
        return view('dashboard.Projects.create', $data);
    }

    public function store(AddProjectRequest $request)
    {
        $data = $request->all();
        $data['user_id'] = auth()->user()->id;
        $project = Project::create($data);
        return redirect()->route('projects.index')->with('success', 'add project successfully');
    }


    public function edit($id)
    {
        if (!Project::find($id)) {
            return redirect()->route('dashboard.project.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $data['latest_projects'] = Project::orderBy('id', 'desc')->take(10)->get();
        $data['project'] = Project::find($id);

        return view('dashboard.Projects.edit', $data);
    }

    public function update(Request $request, Project $project)
    {
        $request_data = $request->all();
        $project->update($request_data);
        return redirect()->route('projects.index')->with('success', 'updated successfully');
    }



    public function show($id)
    {
        if (!Project::find($id)) {
            return redirect()->route('projects.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $this->data['project'] = Project::where('id',$id)->with('tasks')->first();

       // $this->data['tasks'] = Task::where(['project_id' => $id])->get();
        return view('dashboard.Projects.show', $this->data);
    }




    public function delete(Request $request)
    {
        $user = Project::find($request->id);

        if (!$user) return response()->json(['deleteStatus' => false, 'error' => 'Sorry, User is not exists !!']);
        try {
            $user->delete();
            return response()->json(['deleteStatus' => true, 'message' => 'تم الحذف  بنجاح']);
        } catch (Exception $e) {
            return response()->json(['deleteStatus' => false, 'error' => 'Server Internal Error 500']);
        }

        return redirect()->route('projects.index');
    }
}

app/Http/Controllers/Dashboard/TaskController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\createTaskRequest;
use App\Models\Project;
use App\Models\Task;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    public function index()
    {

        $tasks = Task::with('project')->get();
        return view('dashboard.Tasks.index', compact('tasks'));
    }

    public function create()
    {
        $data['latest_tasks'] = Task::orderBy('id', 'desc')->take(10)->get();
        $data['projects'] = Project::all();
        return view('dashboard.Tasks.create', $data);
    }


    public function store(createTaskRequest $request)
    {
        $data = $request->all();
        $project = Task::create($data);
        return redirect()->route('tasks.index')->with('success', 'add project successfully');

    }


    public function edit($id)
    {
        if (!Task::find($id)) {
            return redirect()->route('tasks.index')->with('class', 'danger')->with('message', trans('dash.messages.try_2_access_not_found_content'));
        }
        $data['task'] = Task::find($id);

        return view('dashboard.Tasks.edit', $data);
    }

    public function update(Request $request, Task $task)
    {
        $request_data = $request->all();
        $task->update($request_data);
        return redirect()->route('tasks.index')->with('success', 'updated successfully');
    }


    public function delete(Request $request)
    {
        $user = Task::find($request->id);

        if (!$user) return response()->json(['deleteStatus' => false, 'error' => 'Sorry, User is not exists !!']);
        try {
            $user->delete();
            return response()->json(['deleteStatus' => true, 'message' => 'تم الحذف  بنجاح']);
        } catch (Exception $e) {
            return response()->json(['deleteStatus' => false, 'error' => 'Server Internal Error 500']);
        }

        return redirect()->route('tasks.index');
    }


}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

;

class UserController extends Controller
{


    public function index()
    {
        $users = User::get();
        return view('dashboard.Users.index', compact('users'));
    }


    public function delete(Request $request)
    {
        // here we must validate user id and who can hae access for deleting this user.

        $user = User::find($request->id);

        if (!$user) return response()->json(['deleteStatus' => false, 'error' => 'Sorry, User is not exists !!']);
        try {
            $user->delete();
            return response()->json(['deleteStatus' => true, 'message' => 'تم الحذف  بنجاح']);
        } catch (Exception $e) {
            return response()->json(['deleteStatus' => false, 'error' => 'Server Internal Error 500']);
        }

        return redirect()->route('users.index');
    }


}

resources/views/dashboard/Tasks/create.blade.php
@extends('dashboard.layouts.master')

@section('title', trans('back.create-var',['var'=>trans('back.task')]))


@section('content')


    <!-- Page header -->
    <div class="page-header page-header-default">
        <div class="page-header-content">
            <div class="page-title">
                <h4>
                    <i class="icon-arrow-right6 position-left"></i>
                    <span class="text-semibold">@lang('back.home')</span>
                    - @lang('back.create-var',['var'=>trans('back.task')])
                </h4>
            </div>
        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb">
                <li><a href="{{ url('/task') }}"><i class="icon-home2 position-left"></i> @lang('back.home')</a></li>
                <li><a href="{{ route('tasks.index') }}"><i class="icon-tasks position-left"></i> @lang('back.tasks')
                    </a></li>
                <li class="active">@lang('back.create-var',['var'=>trans('back.task')])</li>
            </ul>

            @include('dashboard.includes.quick-links')
        </div>
    </div>
    <!-- /page header -->



    @include('dashboard.includes.errors')

    <div class="row" style="padding: 15px;">
        <div class="col-md-6">

            <!-- Basic layout-->
            <form action="{{ route('tasks.store') }}" class="form-horizontal" method="post"
                  enctype="multipart/form-data">
                @csrf
                <div class="panel panel-flat">
                    <div class="panel-heading">
                        <h5 class="panel-title"> اضافة تاسك جديد </h5>
                        <div class="heading-elements">
                            <ul class="icons-list">
                                <li><a data-action="collapse"></a></li>
                                <li><a data-action="reload"></a></li>
                                <li><a data-action="close"></a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="panel-body">


                        <div class="form-group">
                            <label class="col-lg-3 control-label">name</label>
                            <div class="col-lg-9">
                                <input type="text" name="task_name" value="" class="form-control"
                                       placeholder="name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label
                                class="col-lg-3 control-label display-block"> {{ trans('dash.name') }} </label>
                            <div class="col-lg-9">
                                <select name="project_id" class="select-border-color border-warning form-control">

                                    @foreach ($projects as $project)
                                        <option value="{{ $project->id }}"> {{ $project->name }} </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-3 control-label">{{ trans('dash.status') }}</label>
                            <div class="col-lg-9">
                                <select name="status" class="select-border-color border-warning">
                                    <option value="on_beginning">on_beginning</option>
                                    <option value="on_progress">on_progress</option>
                                    <option value="finish">finish</option>
                                </select>
                            </div>
                        </div>


                        <div class="text-right">
                            <input type="submit" class="btn btn-primary"
                                   value=" {{ trans('dash.added_and_forward_to_list') }} "/>
                            {{--<input type="submit" class="btn btn-success" name="back" value=" {{ trans('dash.add_and_come_back') }} " />--}}
                        </div>
                    </div>
                </div>
            </form>
            <!-- /basic layout -->

        </div>


        <div class="col-md-6">
            <div class="panel panel-flat">

                <div class="panel-heading">
                    <h5 class="panel-title"> {{ trans('dash.latest_tasks') }} </h5>
                    <div class="heading-elements">
                        <ul class="icons-list">
                            <li><a data-action="collapse"></a></li>
                            <li><a data-action="reload"></a></li>
                            <li><a data-action="close"></a></li>
                        </ul>
                    </div>
                </div>

                <div class="panel-body">

                    <table class="table table-bordered table-hover">
                        <tr class="text-center">
                            <th> name</th>
                        </tr>
                        @forelse($latest_tasks as $task)
                            <tr>
                                <td> {{ $task->name }} </td>
                            </tr>
                        @empty
                            <tr>
                                <td class="alert alert-info">no tasks</td>
                            </tr>
                        @endforelse
                    </table>
                </div>

            </div>
        </div>
    </div>
@stop

resources/views/dashboard/Tasks/edit.blade.php
@extends('dashboard.layouts.master')

@section('title', trans('back.edit-var',['var'=>trans('back.task')]))

@section('content')
    <!-- Page header -->
    <div class="page-header page-header-default">
        <div class="page-header-content">
            <div class="page-title">
                <h4>
                    <i class="icon-arrow-right6 position-left"></i>
                    <span class="text-semibold">@lang('back.home')</span>
                    - @lang('back.edit-var',['var'=>trans('back.task')])
                </h4>
            </div>
        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb">
                <li><a href="{{ url('/dashboard') }}"><i class="icon-home2 position-left"></i> @lang('back.home')</a>
                </li>
                <li><a href="{{ route('tasks.index') }}"><i class="icon-tasks position-left"></i> @lang('back.tasks')
                    </a></li>
                <li class="active">@lang('back.edit-var',['var'=>trans('back.task')])</li>

            </ul>

            @include('dashboard.includes.quick-links')
        </div>
    </div>

    @include('dashboard.includes.errors')


    <div class="row" style="padding-right: 20px;">
        <div class="col-md-6">

            <!-- Basic layout-->
            <form action="{{ route('tasks.update',$task->id) }}" class="form-horizontal" method="post"
                  enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="panel panel-flat">
                    <div class="panel-heading">
                        <h5 class="panel-title"> {{ trans('dash.edit_data') }} </h5>
                        <div class="heading-elements">
                            <ul class="icons-list">
                                <li><a data-action="collapse"></a></li>
                                <li><a data-action="reload"></a></li>
                                <li><a data-action="close"></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label class="col-lg-3 control-label">name</label>
                            <div class="col-lg-9">
                                <input type="text" name="task_name" value="{{$task->task_name}}" class="form-control"
                                       placeholder="name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-3 control-label">status</label>
                            <div class="col-lg-9">
                                <input type="text" name="status" value="{{$task->status}}" class="form-control"
                                       placeholder="status">
                            </div>
                        </div>


                        <div class="text-right">
                            <input type="submit" class="btn btn-primary"
                                   value=" {{ trans('dash.update_and_forword_2_list') }} "/>
                        </div>
                    </div>
                </div>
            </form>
            <!-- /basic layout -->
        </div>

    </div>



@stop

resources/views/dashboard/Tasks/index.blade.php
@extends('dashboard.layouts.master')

@section('title', trans('back.tasks'))

@section('content')

    <!-- Page header -->
    <div class="page-header page-header-default">
        <div class="page-header-content">
            <div class="page-title">
                <h4>
                    <i class="icon-arrow-right6 position-left"></i>
                    <span class="text-semibold">@lang('back.dashboard')</span> - @lang('back.tasks')
                </h4>
            </div>
        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb">
                <li><a href="{{ url('/dashboard') }}"><i class="icon-home2 position-left"></i> @lang('back.home')</a>
                </li>
                <li class="active">@lang('back.tasks')</li>
            </ul>

            @include('dashboard.includes.quick-links')
        </div>
    </div>
    <!-- /page header -->


    @include('dashboard.includes.errors')

    <!-- Basic datatable -->
    <div class="panel panel-flat" dir="" style="margin: 20px;">
        <div class="panel-heading">
            @include('dashboard.includes.table-header', ['collection' => $tasks, 'name' => 'tasks', 'icon' => 'tasks'])
        </div>
        <br>
        <div class="list-icons" style="padding-right: 10px;">
            <a href="{{ route('tasks.create') }}" class="btn btn-success btn-labeled btn-labeled-left"><b><i
                        class="icon-plus2"></i></b>اضافة تاسك جديد</a>
        </div>


        <table class="table datatable-basic" id="tasks" style="font-size: 16px;">
            <thead>
            <tr>
                <th>#</th>
                <th>@lang('back.form-name')</th>
                <th>status</th>
                <th>project</th>
                <th>@lang('back.since')</th>
                <th class="text-center">@lang('back.form-actions')</th>
            </tr>
            </thead>
            <tbody>
            @foreach($tasks as $task)
                <tr id="task-row-{{ $task->id }}">

                    <td>{{ $task->id }}</td>
                    <td><a href="#"> {{ ($task->task_name) }}</a></td>
                    <td>{{ $task->status }}</td>
                    <td>{{ $task->project->name }}</td>
                    <td>{{ $task->created_at->diffForHumans() }}</td>


                    <td class="text-center">
                        <ul class="icons-list">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i
                                        class="icon-menu9"></i></a>

                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li>
                                        <a href="{{ route('tasks.edit',$task->id) }}"> <i
                                                class="icon-database-edit2"></i>@lang('back.edit') </a>
                                    </li>
                                    <li>
                                        <a data-id="{{ $task->id }}" class="delete-action"
                                           href="{{ Url('/task/task/'.$task->id) }}">
                                            <i class="icon-database-remove"></i>@lang('back.delete')
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic datatable -->
@stop

@section('scripts')
    @include('dashboard.layouts.ajax_delete', ['model' => 'task'])



@stop